/***********************************/
/*  Author : Ahmed Ashraf		   */
/* 	DATE   : 13 OCT 2020    	   */
/*  Version: V01				   */
/***********************************/

#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H


/*Options :
 ADC_AREF
 ADC_INTERNAL_2_56
 ADC_AVCC
*/
#define ADC_REF_VOLTAGE			ADC_AVCC
/*Options:
ADC_LEFT_ADJUST
ADC_RIGH_ADJUST
*/
#define ADC_ADJUST_CONTROL		ADC_LEFT_ADJUST

/*Options :
ADC_AUTO_TRIGGER_OFF
ADC_AUTO_TRIGGER_ON
*/
#define ADC_AUTO_TRIGGER		ADC_AUTO_TRIGGER_OFF

/*Options :
ADC_FREE_RUNNING
ADC_ANALOG_COMPARTOR
ADC_INTERRUPT_REQUEST_0
ADC_TIMER_COUNTER_0_COMPARE_MATCH
ADC_TIMER_COUNTER_0_OVERFLOW
ADC_COUNTER_COMPARE_MATCH_B
ADC_TIMER_COUNTER_1_OVERFLOW
ADC_TIMER_COUNTER_1_CAPTURE_EVENT
*/
#define ADC_AUTO_TRIGGER_MODE		ADC_FREE_RUNNING
/*Options :
DIVISION_FACTOR_2
DIVISION_FACTOR_4
DIVISION_FACTOR_8
DIVISION_FACTOR_16
DIVISION_FACTOR_32
DIVISION_FACTOR_64
DIVISION_FACTOR_128	

*/
#define ADC_PRESCALER_DIVISION	DIVISION_FACTOR_128

/*Options
 ADC_INTERRUPT_ENABLE
 ADC_INTERRUPT_DISABLE
  */
#define ADC_INTERRUPT	ADC_INTERRUPT_DISABLE



#endif
